trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-16.04'
container: adoptopenjdk:11-jdk-hotspot
steps:
- script: java --version
- script: ls $(Pipeline.Workspace)
- script: $(Pipeline.Workspace)/s/gradlew build --stacktrace
- script: ls $(Build.SourcesDirectory)/build/libs/
#- publish: $(Pipeline.Workspace)/s/build/libs/*.jar
#  artifact: app-users-jar