trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-16.04'
container: adoptopenjdk:11-jdk-hotspot
steps:
- script: java --version
- script: ls $(Pipeline.Workspace)
- script: $(Pipeline.Workspace)/s/gradlew build --stacktrace
- script: ls $(Build.SourcesDirectory)/build/libs/
- script: ls $(Build.ArtifactStagingDirectory)
#- task: CopyFiles
#  inputs:
#    targetFolder: $(Build.ArtifactStagingDirectory)
#- publish: $(Build.SourcesDirectory)/build/libs/*.jar